#!/usr/bin/env sh 

# mouse
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# layout
yabai -m config window_topmost               on 
yabai -m config window_placement             second_child
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50
yabai -m config layout                       bsp

# opacity/shadows
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_shadow                off 

# borders
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff2fadff
yabai -m config normal_window_border_color   0xff505050

# padding
yabai -m config top_padding                  26
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# custom rules
yabai -m rule --add app='^System Preferences$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Ghidra$' manage=off layer=above
yabai -m rule --add app='^Calculator$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Keychain Access$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Finder$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Preview$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Activity Monitor$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add title='Preferences$' manage=off layer=above grid=4:4:1:1:2:2

echo "yabai configuration loaded..."
