#!/usr/bin/env sh 

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on 
yabai -m config window_shadow                off 
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  26
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   5

# custom rules
yabai -m rule --add app='^System Preferences$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Ghidra$' manage=off layer=normal
yabai -m rule --add app='^Mail$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Calendar$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Calculator$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Keychain Access$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Finder$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Preview$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Activity Monitor$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add app='^Mail$' title='^Inbox' manage=on
yabai -m rule --add app='^Cisco Jabber$' manage=on
yabai -m rule --add title='Preferences$' manage=off layer=above grid=4:4:1:1:2:2
yabai -m rule --add title='^$' manage=off

echo "yabai configuration loaded..."
