[theme]
theme = "dracula"

[icons]
icons = "awesome6"

[[block]]
block = "memory"
format = "$mem_used_percents"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 5

[[block]]
block = "battery"
interval = 10
full_format = "$percentage"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'%a %m-%d-%Y %H:%M')"
