#!/usr/bin/env sh

spacebar -m config text_font         "San Francisco:Bold:12.0"
spacebar -m config icon_font         "San Francisco:Bold:12.0"
spacebar -m config background_color  0xff202020
spacebar -m config foreground_color  0xffa8a8a8
spacebar -m config space_icon_strip  '1: browser' '2: chat' '3: email' '4: calendar' '5: terminals' '6: notes' '7: code' '8: burp' '9: general' '10: general'

echo "spacebar configuration loaded..."
