live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xffa198"
index = 17

[colors.bright]
black = "0x6e7681"
blue = "0x79c0ff"
cyan = "0x56d4dd"
green = "0x56d364"
magenta = "0xd2a8ff"
red = "0xffa198"
white = "0xf0f6fc"
yellow = "0xe3b341"

[colors.normal]
black = "0x484f58"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x3fb950"
magenta = "0xbc8cff"
red = "0xff7b72"
white = "0xb1bac4"
yellow = "0xd29922"

[colors.primary]
background = "0x0d1117"
foreground = "0xb3b1ad"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Meslo LG S"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 2
y = 2
